# Generated by Django 3.2.20 on 2023-08-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush_app', '0003_auto_20230810_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedPost',
        ),
    ]
