# Generated by Django 3.2.20 on 2023-08-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush_app', '0004_delete_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
