# Generated by Django 3.2.20 on 2023-08-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brush_app', '0004_savedbrush'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbrush',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedbrush_set', to='brush_app.post'),
        ),
        migrations.AlterUniqueTogether(
            name='savedbrush',
            unique_together=set(),
        ),
    ]
