# Generated by Django 3.2.20 on 2023-08-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush_app', '0005_comment_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reported_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
