# Generated by Django 3.2.20 on 2023-08-23 11:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush_app', '0006_comment_reported_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='artwork_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
